apiVersion: deploy.cloud.google.com/v1
kind: DeliveryPipeline
metadata:
  name: cloud-run-pipeline
description: Spring PetClinic deployment pipeline
serialPipeline:
  stages:
  - targetId: dev-env
    profiles: [dev]
  - targetId: staging-env
    profiles: [staging]
  - targetId: prod-env
    profiles: [prod]
---
apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: dev-env
description: Cloud Run development service
run:
  location: projects/lgu-demos/locations/europe-west1
---
apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: staging-env
description: Cloud Run staging service
run:
  location: projects/lgu-demos/locations/europe-west1
---
apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: prod-env
description: Cloud Run prod service
requireApproval: true
run:
  location: projects/lgu-demos/locations/europe-west1
