steps:
  - id: Build the application
    name: 'gcr.io/k8s-skaffold/skaffold:slim'
    args: ['skaffold', 'build', '--default-repo', 'europe-west1-docker.pkg.dev/lgu-demos/spring-projects']
  - id: Create a Cloud Deploy release
    name: 'gcr.io/cloud-builders/gcloud'
    args:
      [
        'deploy',
        'releases',
        'create',
        'run-release-${SHORT_SHA}',
        '--skaffold-version=skaffold_preview',
        '--region',
        'europe-west1',
        '--delivery-pipeline',
        'cloud-run-pipeline',
        '--images',
        'spring-petclinic=europe-west1-docker.pkg.dev/lgu-demos/spring-projects:${SHORT_SHA}'
      ]
