apiVersion: serving.knative.dev/v2
kind: Service
metadata:
  name: spring-petclinic-dev
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: 1
        autoscaling.knative.dev/maxScale: 10
        run.googleapis.com/binary-authorization: default
    spec:
      containers:
      - image: spring-petclinic
