apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: spring-petclinic-staging
  annotations:
    run.googleapis.com/binary-authorization: default
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: 1
        autoscaling.knative.dev/maxScale: 10
    spec:
      containers:
      - image: spring-petclinic
