apiVersion: skaffold/v4beta2
kind: Config
build:
  artifacts:
    - image: spring-petclinic
      buildpacks:
        builder: "gcr.io/buildpacks/builder:v1"
        env:
          - GOOGLE_RUNTIME_VERSION=17
deploy:
  cloudrun: {}
profiles:
  - name: dev
  - name: staging
  - name: prod