apiVersion: skaffold/v4beta2
kind: Config
build:
  artifacts:
    - image: spring-petclinic
      buildpacks:
        builder: "gcr.io/buildpacks/builder:v1"
        env:
          - GOOGLE_RUNTIME_VERSION=17
deploy:
  cloudrun: {}
profiles:
  - name: dev
    manifests:
      rawYaml:
        - run-dev.yaml
  - name: staging
    manifests:
      rawYaml:
        - run-staging.yaml
  - name: prod
    manifests:
      rawYaml:
        - run-prod.yaml
